apiVersion: v1
kind: Secret
metadata:
  name: webapp-secrets 
type: Opaque        
stringData:          
  MONGODB_URI: "mongodb://MySuperAdmin:test123@10.10.0.2:27017" 
  SECRET_KEY: "secret123"             